image: php:7.2-cli-alpine

cache:
  paths:
    - vendor/

before_script:
  - apk add git autoconf build-base
  - pecl install xdebug
  - docker-php-ext-install mysqli pdo pdo_mysql
  - docker-php-ext-enable xdebug
  - curl https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar > composer.phar
  - php composer.phar install

test:
  script:
    - vendor/bin/phpunit --configuration phpunit.xml
